# Generated by Django 5.1.2 on 2024-10-24 09:15

import Routing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('Route_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[Routing.models.validate_Route_id])),
                ('user_id', models.IntegerField(unique=True)),
                ('route_name', models.CharField(max_length=255)),
                ('route_origin', models.CharField(max_length=255)),
                ('route_destination', models.CharField(max_length=255)),
                ('route_stops', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
