# Generated by Django 5.1.2 on 2024-10-24 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(default='TP228499', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('vehicle_id', models.IntegerField()),
                ('driver_name', models.CharField(max_length=255)),
                ('Route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Route.route')),
            ],
        ),
    ]
