# Generated by Django 5.1.2 on 2024-10-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(default='TP887140', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
