# Generated by Django 5.1.2 on 2024-10-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0006_alter_trip_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(default='TP20342004', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
