# Generated by Django 5.1.2 on 2024-10-21 17:09

import Booking.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[Booking.models.validate_ticket_id])),
                ('trip_id', models.CharField(max_length=10)),
                ('traveller_name', models.CharField(max_length=255)),
                ('traveller_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Traveller number must be 10 digits', regex='^\\d{10}$')])),
                ('ticket_cost', models.FloatField()),
                ('traveller_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
            ],
        ),
    ]
