# Generated by Django 5.1.2 on 2024-10-20 05:55

import Trip.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[Trip.models.validate_trip_id]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
