# Generated by Django 5.1.2 on 2024-10-20 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Route', '0002_alter_route_route_id_alter_route_user_id'),
        ('Trip', '0002_alter_trip_trip_id_alter_trip_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='Route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Route.route'),
        ),
    ]
