# Generated by Django 5.1.2 on 2024-10-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0003_alter_trip_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
