# Generated by Django 5.1.2 on 2024-10-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0004_alter_trip_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
