# Generated by Django 5.1.2 on 2024-10-20 14:03

import Route.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Route', '0002_alter_route_route_id_alter_route_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='Route_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[Route.models.validate_Route_id]),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_stops',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
