# Generated by Django 5.1.2 on 2024-10-24 06:48

import Route.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Route', '0003_alter_route_route_id_alter_route_route_stops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='Route_id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[Route.models.validate_Route_id]),
        ),
    ]
