# Generated by Django 5.1.2 on 2024-10-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('Route_id', models.CharField(default='RT179344', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('route_name', models.CharField(max_length=255)),
                ('route_origin', models.CharField(max_length=255)),
                ('route_destination', models.CharField(max_length=255)),
                ('route_stops', models.TextField(blank=True)),
            ],
        ),
    ]
