# Generated by Django 5.1.2 on 2024-10-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Route', '0004_alter_route_route_id_alter_route_route_stops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='Route_id',
            field=models.CharField(default='RT46758360', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
