# Generated by Django 5.1.2 on 2024-10-25 16:03

import Route.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Route', '0005_alter_route_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='Route_id',
            field=models.CharField(default=Route.models.generate_route_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
